spring:
  application:
    name: APICanvasStudent
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: postgresql-database
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

  datasource:
    url: jdbc:postgresql://localhost:5432/apiCanvasStudent
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true