# Server Configuration
server.port=8081

# Application Name
spring.application.name=APICanvasStudent

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5431/apiCanvasStudent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# RabbitMQ Configuration
spring.rabbitmq.addresses=amqps://auwifbhi:iCWziig5eNuhcZbJP5WeFX5ns3Bd2Wvw@jaragua.lmq.cloudamqp.com/auwifbhi

# Custom Broker Configuration
broker.queue.login.name=exchange.login