CREATE TABLE grade_tb(
    grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade NUMERIC NOT NULL,
    weight NUMERIC NOT NULL,
    user_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    CONSTRAINT fk_user_subject FOREIGN KEY (user_id,subject_id) REFERENCES user_subject_tb(user_id,subject_id)
);