server.port=8082
spring.application.name=login

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.datasource.url=jdbc:postgresql://localhost:5431/ms-login
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.rabbitmq.addresses=amqps://auwifbhi:iCWziig5eNuhcZbJP5WeFX5ns3Bd2Wvw@jaragua.lmq.cloudamqp.com/auwifbhi
broker.queue.login.name=exchange.login