server:
  port: 8082
spring:
  application:
    name: login
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

  datasource:
    url: jdbc:postgresql://localhost:5431/ms-login
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    addresses: amqps://auwifbhi:iCWziig5eNuhcZbJP5WeFX5ns3Bd2Wvw@jaragua.lmq.cloudamqp.com/auwifbhi
broker:
  queue:
    login:
      name: exchange.login